apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: danilo-fukuoka #CHANGE-ME
  labels:
    app: my-pod
spec:
  serviceAccountName: danilo-fukuoka #CHANGE-ME
  automountServiceAccountToken: false
  restartPolicy: Never
  containers:
    - name: my-pod
      image: danilofukuoka168/offsite-2025-k8s:v2
      imagePullPolicy: Always
      env:
        - name: MONGODB_URI
          value: "mongodb+srv://cluster0.3vy6o.mongodb.net"
        - name: BONUSLY
          value: danilo-fukuoka #CHANGE-ME
      volumeMounts:
        - name: oidc-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "250m"
  volumes:
    - name: oidc-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 600 #10 minutes