apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-mongodb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-mongodb-app
  template:
    metadata:
      labels:
        app: java-mongodb-app
    spec:
      containers:
        - name: java-mongodb-app
          image: danilofukuoka/imds-java:latest  # Your Docker image
          ports:
            - containerPort: 8080
          env:
            - name: CONNECTION_STRING
              value: "mongodb+srv://cluster0.xxxx.mongodb.net"  # MongoDB Connection String. Example: mongodb+srv://cluster0.cwfdw.mongodb.net
            - name: APP_REGISTRATION_CLIENT_ID
              value: ""  # Azure App Registration Client ID.
            #- name: MANAGED_IDENTITY_CLIENT_ID
            #  value: ""  # Azure Managed Identity Client ID


# Addionally, add the Azure Managed Identity Object ID to Atlas Database Access.